---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: aurora-dx-evdi
# description will be included in the image's metadata
description: Aurora developer experience with DisplayLink drivers

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://negativo17.org/repos/fedora-multimedia.repo

  - type: akmods
    base: main
    install:
      - evdi

  - type: default-flatpaks
    notify: true 
    system:
      install:
        - org.mozilla.firefox

  - type: signing 

